# Generated by Django 5.1.6 on 2025-03-01 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nms_N1_1", models.CharField(max_length=50)),
                ("nms_N1_2", models.CharField(max_length=50)),
                ("nms_N1_3", models.CharField(max_length=50)),
                ("nms_N1_4", models.CharField(max_length=50)),
                ("nms_N2_1", models.CharField(max_length=50)),
                ("nms_N2_2", models.CharField(max_length=50)),
                ("nms_N2_3", models.CharField(max_length=50)),
                ("nms_N2_4", models.CharField(max_length=50)),
                ("nms_N3_1", models.CharField(max_length=50)),
                ("nms_N3_2", models.CharField(max_length=50)),
                ("nms_N3_3", models.CharField(max_length=50)),
                ("nms_N3_4", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="UserSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seq_N1_1", models.CharField(max_length=20)),
                ("seq_N1_2", models.CharField(max_length=20)),
                ("seq_N1_3", models.CharField(max_length=20)),
                ("seq_N1_4", models.CharField(max_length=20)),
                ("seq_N2_1", models.CharField(max_length=20)),
                ("seq_N2_2", models.CharField(max_length=20)),
                ("seq_N2_3", models.CharField(max_length=20)),
                ("seq_N2_4", models.CharField(max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
