# Generated by Django 5.1.6 on 2025-03-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestTableMigration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_field", models.CharField(max_length=20)),
                ("some_field", models.IntegerField(max_length=20)),
                ("another_char_field", models.CharField(max_length=20)),
            ],
        ),
    ]
